package br.com.clinic.viewer;

import br.com.clinic.facade.Facade;
import br.com.clinic.model.Cargo;
import br.com.clinic.model.CidadeEstado;
import br.com.clinic.model.Endereco;
import br.com.clinic.model.Funcionario;
import br.com.clinic.util.JtextFieldSomenteNumeros;
import br.com.clinic.util.Util;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author José
 */
public class JfCadastroFuncionario extends javax.swing.JFrame {

    private Facade facade;
    private JdPesquisaFuncionario jdPesquisaFunc;
    private JdCadastroCargo jdCadastroCargo;
    private JdPesquisaCidadeEstado jdPesquisaCE;
    private Long setId;
    private Funcionario funcionario;
    private CidadeEstado cidadeEstado;

    //ação dos buttons aceitar e negar
    private boolean actionEdit;
    private boolean actionInsert;

    public JfCadastroFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cadastro Funcionario");

        facade = new Facade();
        jdPesquisaFunc = new JdPesquisaFuncionario(this, true);
        jdCadastroCargo = new JdCadastroCargo(this, true);
        jdPesquisaCE = new JdPesquisaCidadeEstado(this, true);

        jtId.setEditable(false);
        jtDataCadastro.setEditable(false);

        //so aparece quando necessário
        jbAceitar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlCPf = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##"); 
            jtCpf = new javax.swing.JFormattedTextField(cpf); 
        } 
        catch (Exception e){ 
        }
        jtContato = new javax.swing.JTabbedPane();
        jpEndereco = new javax.swing.JPanel();
        jlBairro = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jlRua = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jlCep = new javax.swing.JLabel();
        jtCep = new JtextFieldSomenteNumeros(8);
        jtNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtUf = new javax.swing.JTextField();
        jbBuscaCidade = new javax.swing.JButton();
        jpContato = new javax.swing.JPanel();
        jlTelefone = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter tel= new javax.swing.text.MaskFormatter("(##)####-####"); 
            jtTelefone = new javax.swing.JFormattedTextField(tel); 
        } 
        catch (Exception e){ 
        }
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jpObs = new javax.swing.JPanel();
        jlObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtObs = new javax.swing.JTextArea();
        jlDataNas = new javax.swing.JLabel();
        jtDataNas = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter date = new javax.swing.text.MaskFormatter("##/##/####"); 
            jtDataNas = new javax.swing.JFormattedTextField(date); 
        } 
        catch (Exception e){ 
        }
        jlId = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jlDataCadastro = new javax.swing.JLabel();
        jtDataCadastro = new javax.swing.JTextField();
        jlCargo = new javax.swing.JLabel();
        jcbCargo = new javax.swing.JComboBox();
        jtContato1 = new javax.swing.JTabbedPane();
        jpEndereco1 = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jpCadastro = new javax.swing.JPanel();
        jbCadastrar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbAceitar = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdicionais = new javax.swing.JMenu();
        jmiCargo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlNome.setText("Nome: ");

        jtNome.setToolTipText("");
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });

        jlCPf.setText("CPF: ");

        jtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCpfActionPerformed(evt);
            }
        });

        jlBairro.setText("Bairro:");

        jlRua.setText("Rua:");

        jtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaActionPerformed(evt);
            }
        });

        jlNumero.setText("Número:");

        jlCidade.setText("Cidade:");

        jtCidade.setToolTipText("");
        jtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeActionPerformed(evt);
            }
        });

        jlCep.setText("CEP:");

        jLabel1.setText("UF:");

        jbBuscaCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinic/img/lupa_128x128.png"))); // NOI18N
        jbBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEnderecoLayout = new javax.swing.GroupLayout(jpEndereco);
        jpEndereco.setLayout(jpEnderecoLayout);
        jpEnderecoLayout.setHorizontalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtBairro)))
                        .addGap(119, 119, 119))
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jlCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(263, Short.MAX_VALUE))))
        );
        jpEnderecoLayout.setVerticalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRua)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumero)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCidade)
                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCep)
                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jtContato.addTab("Endereço", jpEndereco);

        jlTelefone.setText("Celular:");

        jlEmail.setText("Email:");

        jtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpContatoLayout = new javax.swing.GroupLayout(jpContato);
        jpContato.setLayout(jpContatoLayout);
        jpContatoLayout.setHorizontalGroup(
            jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpContatoLayout.createSequentialGroup()
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtTelefone))
                    .addGroup(jpContatoLayout.createSequentialGroup()
                        .addComponent(jlEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jpContatoLayout.setVerticalGroup(
            jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtContato.addTab("Contato", jpContato);

        jlObs.setText("Observações do Cliente:");

        jtObs.setColumns(20);
        jtObs.setRows(5);
        jScrollPane1.setViewportView(jtObs);

        javax.swing.GroupLayout jpObsLayout = new javax.swing.GroupLayout(jpObs);
        jpObs.setLayout(jpObsLayout);
        jpObsLayout.setHorizontalGroup(
            jpObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlObs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jpObsLayout.setVerticalGroup(
            jpObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jtContato.addTab("Observações", jpObs);

        jlDataNas.setText("Data de Nascimento:");

        jlId.setText("ID:");

        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });

        jlDataCadastro.setText("Data do Cadastro:");

        jlCargo.setText("Cargo:");

        jlLogin.setText("Account:");

        jlSenha.setText("Password:");

        jtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jpEndereco1Layout = new javax.swing.GroupLayout(jpEndereco1);
        jpEndereco1.setLayout(jpEndereco1Layout);
        jpEndereco1Layout.setHorizontalGroup(
            jpEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEndereco1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jlLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpEndereco1Layout.setVerticalGroup(
            jpEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEndereco1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSenha)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jtContato1.addTab("Account", jpEndereco1);

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtContato)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jtContato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpPrincipalLayout.createSequentialGroup()
                                    .addComponent(jlNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpPrincipalLayout.createSequentialGroup()
                                    .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPrincipalLayout.createSequentialGroup()
                                            .addComponent(jlCargo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPrincipalLayout.createSequentialGroup()
                                            .addComponent(jlCPf)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jlDataNas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtDataNas)))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jlId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlDataCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataCadastro)
                    .addComponent(jtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPf)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataNas)
                    .addComponent(jtDataNas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCargo)
                    .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jtContato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAceitar.setText("☑");
        jbAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceitarActionPerformed(evt);
            }
        });

        jbRefresh.setText("☒");
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroLayout = new javax.swing.GroupLayout(jpCadastro);
        jpCadastro.setLayout(jpCadastroLayout);
        jpCadastroLayout.setHorizontalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAceitar)
                .addGap(22, 22, 22))
        );
        jpCadastroLayout.setVerticalGroup(
            jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbBuscar)
                    .addComponent(jbEditar)
                    .addComponent(jbDeletar)
                    .addComponent(jbAceitar)
                    .addComponent(jbRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmAdicionais.setText("Adicionais");
        jmAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdicionaisActionPerformed(evt);
            }
        });

        jmiCargo.setText("Cadastro Cargo");
        jmiCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargoActionPerformed(evt);
            }
        });
        jmAdicionais.add(jmiCargo);

        jMenuBar1.add(jmAdicionais);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jpCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed

    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCpfActionPerformed

    }//GEN-LAST:event_jtCpfActionPerformed

    private void jtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaActionPerformed

    private void jtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeActionPerformed

    private void jtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        limparForm();
        jbAceitar.setEnabled(true);
        actionInsert = true;
        preencherComboBox();
        esconderButtons();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        jdPesquisaFunc.setVisible(true);
        jdPesquisaFunc.limparTabela();
        funcionario = jdPesquisaFunc.getFuncionario();
        //JOptionPane.showMessageDialog(null,cliente);
        buscarFuncionario(funcionario);
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        try {
            if (jtId.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Prmeiro busque um cliente");
            } else {
                int result = JOptionPane.showConfirmDialog(null, "Deseja excluir o cliente?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    if (funcionario != null) {
                        deletarFuncionario(funcionario);
                        limparForm();
                    }
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(JfCadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed

    }//GEN-LAST:event_jtIdActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        try {
            if (jtId.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Prmeiro busque um cliente");
            } else {
                jbAceitar.setEnabled(true);
                esconderButtons();
                //o actionEdit recebendo true faz com que seja possível editar-lo apertando o jbAceitar
                actionEdit = true;
            }
        } catch (Exception ex) {
            Logger.getLogger(JfCadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceitarActionPerformed

        if (actionEdit == true) {
            try {
                if (funcionario != null) {

                    editarFuncionario(funcionario);
                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Erro: " + e.getMessage());
            }
        }
        if (actionInsert == true) {
            cadastrarFuncionario();
        }

        actionEdit = false;
        actionInsert = false;
    }//GEN-LAST:event_jbAceitarActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        limparForm();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jmiCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargoActionPerformed
        jdCadastroCargo.setVisible(true);
    }//GEN-LAST:event_jmiCargoActionPerformed

    private void jmAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdicionaisActionPerformed

    }//GEN-LAST:event_jmAdicionaisActionPerformed

    private void jbBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaCidadeActionPerformed
        jdPesquisaCE.setVisible(true);
        jdPesquisaCE.limparTabela();
        CidadeEstado aux = jdPesquisaCE.getCidadeEstado();
        if(aux != null){
            cidadeEstado = aux;
            jtCidade.setText(cidadeEstado.getNomeCidade());
            jtUf.setText(cidadeEstado.getNomeEstado());
        }
    }//GEN-LAST:event_jbBuscaCidadeActionPerformed

    private void jtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLoginFocusLost
        boolean aux = true;
        try {
            for(Funcionario u: facade.funcionarioListar())
                if(u.getLogin().equals(jtLogin.getText()))
                    aux = false;
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Error:" + ex.getMessage());
        }
        if(!aux){
            JOptionPane.showMessageDialog(null, "Login existente!");
            jtLogin.setText(null);
        }
    }//GEN-LAST:event_jtLoginFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAceitar;
    private javax.swing.JButton jbBuscaCidade;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JComboBox jcbCargo;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCPf;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlDataCadastro;
    private javax.swing.JLabel jlDataNas;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlObs;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JMenu jmAdicionais;
    private javax.swing.JMenuItem jmiCargo;
    private javax.swing.JPanel jpCadastro;
    private javax.swing.JPanel jpContato;
    private javax.swing.JPanel jpEndereco;
    private javax.swing.JPanel jpEndereco1;
    private javax.swing.JPanel jpObs;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCep;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTabbedPane jtContato;
    private javax.swing.JTabbedPane jtContato1;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtDataCadastro;
    private javax.swing.JTextField jtDataNas;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtLogin;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextArea jtObs;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTextField jtUf;
    // End of variables declaration//GEN-END:variables

    void preencherComboBox() {
        try {
            DefaultComboBoxModel dm = new DefaultComboBoxModel();
            dm.removeAllElements();
            if (facade.cargoListar() != null) {
                for (Cargo s : facade.cargoListar()) {
                    dm.addElement(s);
                }
                jcbCargo.setModel(dm);
            } else {
                JOptionPane.showMessageDialog(null, "Lista vazia! Cadastre setores!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());
        }
    }

    void limparComboBox() {
        try {
            DefaultComboBoxModel dm = new DefaultComboBoxModel();
            dm.removeAllElements();
            jcbCargo.setModel(dm);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());
        }
    }

    public void cadastrarFuncionario() {
        try {

            if (this.jtNome.getText().equals("") || jcbCargo.getSelectedItem()==null) {
                JOptionPane.showMessageDialog(null, "Informe o cliente ou Cargo");
            } else {
                Endereco e = new Endereco();
                e.setRua(this.jtRua.getText());
                e.setBairro(this.jtBairro.getText());
                if(cidadeEstado!=null)
                    e.setCidadeEstado(cidadeEstado);
                e.setNumero(this.jtNumero.getText());
                
                e.setCep(this.jtCep.getText());

                Funcionario f = new Funcionario();
                f.setEndereco(e);
                f.setNome(this.jtNome.getText());
                f.setCpf(this.jtCpf.getText());
                f.setDataNas(Util.stringToDate(this.jtDataNas.getText()));
                f.setTelefone(this.jtTelefone.getText());
                f.setEmail(this.jtEmail.getText());
                f.setObs(this.jtObs.getText());
                
                if(jtLogin.getText() != null){
                    boolean aux = true;
                    for(Funcionario fun: facade.funcionarioListar())
                        if(jtLogin.getText().equals(fun.getLogin()))
                            aux = false;
                    if(aux){
                       f.setLogin(jtLogin.getText());
                       f.setSenha(jpfSenha.getText());
                       f.setCargo((Cargo) jcbCargo.getSelectedItem());

                        facade.funcionarioCadastrar(f);
                        buscarFuncionario(f);
                        mostraButtons();
                        JOptionPane.showMessageDialog(null, "Cliente: " + f.getId() + " cadastrado com sucesso!");
                    }else
                       JOptionPane.showMessageDialog(null, "Login já existe"); 
                } 
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());
        }
    }

    public void buscarFuncionario(Funcionario f) {
        try {
            //if(facade.ClienteBuscar(setId)!= null){ 
            //TRAVA O CADASTRAR PARA N CADASTRAR UM BUSCADO
            //jbCadastrar.setEnabled(false);

            if (f != null) {
                funcionario = f;
                this.jtId.setText(f.getId().toString());
                this.jtDataCadastro.setText(Util.dateToString(f.getDataCadastro()));
                this.jtNome.setText(f.getNome());
                this.jtCpf.setText(f.getCpf());
                this.jtDataNas.setText(Util.dateToString(f.getDataNas()));
                this.jtRua.setText(f.getEndereco().getRua());
                this.jtBairro.setText(f.getEndereco().getBairro());
                if(cidadeEstado!=null)   
                    this.jtCidade.setText(cidadeEstado.toString());
                this.jtNumero.setText(f.getEndereco().getNumero());
                this.jtCep.setText(f.getEndereco().getCep());
                this.jtTelefone.setText(f.getTelefone());
                this.jtEmail.setText(f.getEmail());
                this.jtObs.setText(f.getObs());
                this.jtLogin.setText(f.getLogin());
                this.jpfSenha.setText(f.getSenha());
                
                DefaultComboBoxModel dm = new DefaultComboBoxModel();
                this.jcbCargo.removeAllItems();
                try {
                    if (facade.cargoListar() != null) {
                        if(f.getCargo()!=null){
                            dm.addElement(f.getCargo());
                            for (Cargo c : facade.cargoListar()) {
                                if(!Objects.equals(f.getCargo().getId(), c.getId()))
                                    dm.addElement(c);
                            }
                            jcbCargo.setModel(dm);
                        }else{
                            preencherComboBox();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Lista vazia! Cadastre setores!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    System.out.println("Erro: " + e.getMessage());
                }

            } else {
                limparForm();
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());
        }

    }

    //COLOCAR TUDO PRA CLIENTE
    public void editarFuncionario(Funcionario f) throws Exception {

        try {
        if(f!=null){
            jtLogin.setEditable(false);
            if (facade.funcionarioBuscar(f.getId()) != null) {
                f.setNome(this.jtNome.getText());
                f.setCpf(this.jtCpf.getText());
                f.setDataNas(Util.stringToDate(this.jtDataNas.getText()));
                f.setTelefone(this.jtTelefone.getText());
                f.setEmail(this.jtEmail.getText());
                f.setObs(this.jtObs.getText());
                f.getEndereco().setRua(this.jtRua.getText());
                f.getEndereco().setBairro(this.jtBairro.getText());
                if(cidadeEstado!=null)
                    f.getEndereco().setCidadeEstado(cidadeEstado);
                f.getEndereco().setNumero(this.jtNumero.getText());
                f.getEndereco().setCep(this.jtCep.getText());
                f.setSenha(this.jpfSenha.getText());
                f.setCargo((Cargo) jcbCargo.getSelectedItem());

                if(jcbCargo.getSelectedItem() == null || jtNome.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Informe o cliente ou Cargo");
                    limparForm();
                }else{ 
                    facade.funcionarioEditar(f);
                    buscarFuncionario(f);
                    mostraButtons();
                    JOptionPane.showMessageDialog(null, "Cliente: " + f.getId() + " editado com sucesso!");    
                }
                jtLogin.setEditable(true);
            }
        }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());
        }

    }

    public void deletarFuncionario(Funcionario f) {
        try {
            if (facade.funcionarioBuscar(f.getId()) != null) {
                facade.funcionarioDeletar(f);
                JOptionPane.showMessageDialog(null, "Cliente: " + f.getId() + " excluido com sucesso!");
            }
        } catch (Exception ex) {
            Logger.getLogger(JfCadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void limparForm() {
        jtId.setText(null);
        jtDataCadastro.setText(null);
        jtNome.setText(null);
        jtCpf.setText(null);
        jtLogin.setText(null);
        jpfSenha.setText(null);
        jtDataNas.setText(null);
        jtRua.setText(null);
        jtBairro.setText(null);
        jtCidade.setText(null);
        jtUf.setText(null);
        jtNumero.setText(null);
        jtCep.setText(null);
        jtTelefone.setText(null);
        jtEmail.setText(null);
        jtObs.setText(null);

        jbCadastrar.setEnabled(true);
        jbDeletar.setEnabled(true);
        jbEditar.setEnabled(true);
        jbBuscar.setEnabled(true);

        jbAceitar.setEnabled(false);

        actionEdit = false;
        actionInsert = false;

        limparComboBox();
    }

    public void esconderButtons() {
        jbCadastrar.setEnabled(false);
        jbDeletar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbBuscar.setEnabled(false);
    }

    public void mostraButtons() {
        jbCadastrar.setEnabled(true);
        jbDeletar.setEnabled(true);
        jbEditar.setEnabled(true);
        jbBuscar.setEnabled(true);

        jbAceitar.setEnabled(false);
    }
}
