/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinic.viewer;


import javax.swing.JOptionPane;

/**
 *
 * @author GENPAC
 */
public class JfPrincipal extends javax.swing.JFrame {

    
    private JfCadConf jfCadConf;
    private JfCadastroLancamento jfCadastroLancamento;
    private JfColeta jfColeta;
    private JfExame jfExame;
    private JdLogin jdLogin;
    
    public JfPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tela Principal");
        
        jfCadConf = new JfCadConf();
        jfCadastroLancamento = new JfCadastroLancamento();
        jfColeta = new JfColeta();
        jfExame = new JfExame();
        jdLogin = new JdLogin(this,true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbLancamento = new javax.swing.JButton();
        jbCadConf = new javax.swing.JButton();
        jbColeta = new javax.swing.JButton();
        jbExamina = new javax.swing.JButton();
        jbEntrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbLancamento.setText("LANÇAMENTO");
        jbLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLancamentoActionPerformed(evt);
            }
        });

        jbCadConf.setText("CAD E CONF");
        jbCadConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadConfActionPerformed(evt);
            }
        });

        jbColeta.setText("COLETA");
        jbColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbColetaActionPerformed(evt);
            }
        });

        jbExamina.setText("EXAME");
        jbExamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExaminaActionPerformed(evt);
            }
        });

        jbEntrega.setText("ENTREGA");
        jbEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLancamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jbCadConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbExamina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEntrega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExamina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jbCadConf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadConfActionPerformed
        jfCadConf.setVisible(true);
    }//GEN-LAST:event_jbCadConfActionPerformed

    private void jbLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLancamentoActionPerformed
        jfCadastroLancamento.setVisible(true);
    }//GEN-LAST:event_jbLancamentoActionPerformed

    private void jbColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbColetaActionPerformed
        jdLogin.limpaForm();
        jdLogin.setVisible(true);
        if(jdLogin.getFuncionario()!=null){
            jfColeta.setFuncionario(jdLogin.getFuncionario());
            jfColeta.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(null,"Usuario inexistente ou não encontrado!");     
        }    
    }//GEN-LAST:event_jbColetaActionPerformed

    private void jbExaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExaminaActionPerformed
        jdLogin.limpaForm();
        jdLogin.setVisible(true);
        if(jdLogin.getFuncionario()!=null){
            jfExame.setFuncionario(jdLogin.getFuncionario());
            jfExame.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(null,"Usuario inexistente ou não encontrado!");     
        } 
    }//GEN-LAST:event_jbExaminaActionPerformed

    private void jbEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadConf;
    private javax.swing.JButton jbColeta;
    private javax.swing.JButton jbEntrega;
    private javax.swing.JButton jbExamina;
    private javax.swing.JButton jbLancamento;
    // End of variables declaration//GEN-END:variables
}
